services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: shubhamwagh
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgrs
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

networks:
  postgres:
    driver: bridge

volumes:
  postgres: