server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    username: "postgres"
    password: "postgres"
    url: jdbc:postgresql://localhost:5432/notification_micro
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true