server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: "postgres"
    password: "postgres"
    url: jdbc:postgresql://localhost:5432/fraud_micro
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true